### ISSUE TITLE
Versioned Iterations

### ISSUE THREAD

**Issue by modpluz** [Lever-age/frontend#37]
Right now, we have a WIP version (angular 2) of this repo that sits in the `develop` branch.

We should rather have this (and future iterations) versioned. e.g. `feature/[BRIEF-FEATURE-NAME]`.

**Comment by lottspot** [comment]
I think this is a good suggestion. Maybe we should fork the work that's been done on the angular frontend onto a different branch and rewind `develop`. What do you think @crsmyz?

**Comment by lottspot** [comment]
The angular2 work has been broken out into the [feature/angular2 branch](https://github.com/Lever-age/frontend/tree/feature/angular2) and the develop branch has been rewinded to the pre-angular work point.
