### ISSUE TITLE
Base Template

### ISSUE THREAD

**Issue by lottspot** [Lever-age/frontend#91]
Create a common base template to include the following elements:

- [ ] Header
- [ ] Footer
- [x] Navigation
- [x] `<script>` tag to include `app.js`

**Comment by lottspot** [comment]
@modpluz currently working on the navigation part of that

**Comment by modpluz** [comment]
Navigation resolved in #92.

**Comment by lottspot** [comment]
Moved to: https://github.com/Lever-age/leverage/issues/41
